appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ggsRSFuyc9bKj2GlJucu7pWV+xltZjTumKqFEZTePuVQoeSUyZoO7io1d+c8YZIhuzmUjiKejXI2IbrtVzRV15ekSFjwhrBveDxmHwJq+PR61Ln13JPZGKhybWPPoa+ZDTgAhLIg2eDaDgg+n2uBnGsRXixNwwyoCXONbGFmgTtOPNqFU6F85bpxaYHT1g81XVRcpHf+XIhz2F7CxuAb4/O93dur+d8y1Dc5oSCBXnC1KTgPFecgfRg1KsdhsLVyd7MsMGOETfrdNkr9HpHJDn0/+kTS6FgbcMiqpfVa/D+fY+PMO+NdQf8AV/4x2WIx129plTQ+zBUmO01y0U6qOwdBTXbu5Naub5ipz4i0eaEeRbw8SjZQEhNAcywH6/Xlqsk/aVk5LCW4LV0UJ+SRVHj1D2evil4UdO9WZm2KAZjk7zsksqQoPWtkDWnr2Jtri8Oqtm5O5W0PJpIDZzg0rtLheKnn9dqh7SKqqQ0wa4DWGbAIP08EOpvg1pDrrXdNdCmC99AWlqXw0RgOJlTSYv5G+l+HXx6mRM/H/dz11o/Eng+IOOkJDgDWgIbT1KBWLRER4B7YM+NQkuS3SA2QMMBf0E+LU0BHIESB8bWhcfRFelDIntb8COMpqYNqtsdqLI2sXl9LsvcNJm+WwKiG/tyTgORPH9/wVLGlnOliUPk=
conda_forge_output_validation: true
